# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
            ],
            options={
                'verbose_name_plural': '网站规程',
            },
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': '网站设置'},
        ),
        migrations.AlterModelOptions(
            name='sitecategory',
            options={'verbose_name_plural': '网站分类'},
        ),
        migrations.AddField(
            model_name='siterule',
            name='sitename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_name', to='books.Site'),
        ),
    ]
